# Generated by Django 2.2.2 on 2019-06-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedata',
            name='filename',
            field=models.CharField(default='un', max_length=100),
            preserve_default=False,
        ),
    ]
